### ISSUE TITLE
Sounds don't work in 1.20.1 can you update it

### ISSUE THREAD

**Issue by Batman2741** [eccentricdevotion/TARDIS-SoundResourcePack-Bedrock#1]

**Comment by eccentricdevotion** [comment]
I can't test on a server right now, but the sounds play using the `/playsound` command in a single player world on my iPhone

**Comment by eccentricdevotion** [comment]
As far as I know there are no changes in format of sounds in resource packs for 1.20.x that need updating

**Comment by eccentricdevotion** [comment]
I can't hear sounds as a floodgate bedrock player on a server with geyser, but I've no idea how to fix it...

**Comment by Batman2741** [comment]
> I can't hear sounds as a floodgate bedrock player on a server with geyser, but I've no idea how to fix it...
> 

It my be the way in which TARDIS is executing the sound as sound commands have gotten extremely specific on bedrock

**Comment by eccentricdevotion** [comment]
TARDIS uses Bukkit API to play sounds it doesn't issue commands...
The issue is most likely related to how geyser/floodgate deals with the sounds (if they do at all).

**Comment by eccentricdevotion** [comment]
OK, got it working - there is nothing wrong with the pack as it is...

1. Install latest Geyser and Floodgate plugins
2. Install the [TARDIS-Sounds-Bedrock.mcpack](https://github.com/eccentricdevotion/TARDIS-SoundResourcePack-Bedrock/releases/download/v0.0.2/TARDIS-Sounds-Bedrock.mcpack) into the _plugins/Geyser-Spigot/packs/_ folder
3. Install the TARDIS-Sounds-Bedrock.mcpack on your Bedrock device
4. Install the [GeyserOptionalPack.mcpack](https://ci.opencollab.dev/job/GeyserMC/job/GeyserOptionalPack/job/master/lastSuccessfulBuild/artifact/GeyserOptionalPack.mcpack) on your Bedrock device
5. Add both packs to your Global Resources in your Bedrock device settings
